### ISSUE TITLE
After using your EFI, you will restart after running - V

### ISSUE THREAD

**Issue by Herrengit** [serdeliuk/hackint0sh#1]
The difference between the computer configuration and you is that my graphics card is gtx1660. I already have an EFI that can drive 10.15.4. I want to try the EFI, but it's strange that it will restart automatically after running - V

**Comment by serdeliuk** [comment]
Hi, please use this thread to ask any questions and provide more informations about your configuration, if nvidia video card is different then other things could differ, most notorious is nvme drive which if it is unsupported can generate this kind of issues, kernel panics and restarts.

https://www.tonymacx86.com/threads/info-asus-rog-strix-g531gt-hackintosh-mojave-and-or-catalina-install.287480/
